### ISSUE TITLE
feedback TTT Chapter 9 Version Control

### ISSUE THREAD

**Issue by juliapauquet** [BERD-NFDI/BERD-reproducible-research-course#9]
hi @RabeaMue! 

First of all, this looks amazing! :) I really like your use of visuals and your calm and confident manner of explaining Git in the video. 
I just had a look at Lennarts remarks and I think he already mentioned so much! So here are just some more comments (mind you, this is already looking so good, so these are just tiny things really). 

- Maybe add another sentence about version control in general to the beginning, and explain why it makes sense to use a distributed VC instead of local or centralized types, then indicate that Git is one of those.

- I think it might be helpful to add a visualization for explaining the differences between Git, GitLab and Github (maybe like a tree, or umbrella shape, something like that :)) 

- On your video: I don't know if its possible but the screen recording is a bit grainy - maybe its still possible to export in a higher definition? No worries if not, it still works fine

- maybe add a table with the most common commands and what they do, so people can find this information on the page quickly when they get started

**Comment by RabeaMue** [comment]
Thank you @juliapauquet ! :smiley:

**Comment by RabeaMue** [comment]
Added suggestions here https://github.com/BERD-NFDI/BERD-reproducible-research-course/pull/10
